  - name: uji coba menjalankan docker container
    hosts: container-test-i
    become: false
    tasks:
    - name: Copy file to remote host
      copy:
        src: /home/ivanz/Coding/btj-academy/raw_file
        dest: "{{dir_path}}"
    - name: Build container image
      docker_image:
        name: "{{image_p}}"
        build:
          path: "{{dir_path}}"
        state: present
    - name: Deploy container
      docker_container:
        name: simple-task-ansible-i
        image: "{{image_p}}"
        interactive: true
        tty: true
        exposed_ports:
          - 4321